@startuml

(*)  --> salt
note left:random 32byte
(*) --> password
(*) --> privateKey
note right: 32byte
(*) --> iv
note left: random 16byte
password --> func_pbkdf2
note left
    c     : 262144
    dklen : 32byte
    prf   : hmac-sha256
end note
salt --> func_pbkdf2
func_pbkdf2 --> derivedKey
note right: 32byte
derivedKey --> derivedKeyLow
note left: 16byte
derivedKey --> derivedKeyHigh
note left: 16byte
iv --> func_aes128ctr
derivedKeyLow --> func_aes128ctr
privateKey --> func_aes128ctr
func_aes128ctr --> cipherText
note right:32byte
derivedKeyHigh --> func_SHA3
cipherText --> func_SHA3
func_SHA3 --> MAC
note left:32byte
MAC -->(*)
cipherText --> (*)
@enduml